# Generated by Django 2.2.4 on 2024-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
