# Generated by Django 2.2.4 on 2024-05-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0003_auto_20240519_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='newtork',
            new_name='network',
        ),
    ]
