# Generated by Django 2.2.4 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0004_auto_20240519_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
