# Generated by Django 2.2.4 on 2024-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='gener',
            field=models.TextField(default='Adventure'),
        ),
    ]
