# Generated by Django 2.2.4 on 2024-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_message',
            field=models.TextField(default=''),
        ),
    ]
