# Generated by Django 2.2.4 on 2024-05-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_actor_app', '0002_auto_20240517_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url_image',
            new_name='image_url',
        ),
    ]
