# Generated by Django 2.2.4 on 2024-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_actor_app', '0004_auto_20240517_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rental_rate',
            field=models.DecimalField(decimal_places=1, default=4.99, max_digits=3),
        ),
    ]
