# Generated by Django 2.2.4 on 2024-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(related_name='books', to='many_to_many_app.Publisher'),
        ),
    ]
